import Navbar from './components/Navbar/Navbar'
import CustomersBoard from './components/customers/CustomersBoard'
import Dashboard from './components/dashboard/Dashboard'
import History from './components/history/HistoryBoard'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="it">
      <body>
        <Navbar/>
        <Dashboard/>
        <div className='sub-dashboards-wrapper'>
          <CustomersBoard/>
          <History/>
        </div>
        
      </body>
    </html>
  )
}
